spring:
  config:
    import: optional:classpath:application-secrets.yml
  application:
    name: cowrite

  datasource:
    url: jdbc:postgresql://localhost:5432/cowrite_user_service_db
    driver-class-name: org.postgresql.Driver

  jpa:
    defer-datasource-initialization: false
    generate-ddl: false
    hibernate:
      ddl-auto: none
      dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

  sql:
    init:
      mode: never

  data:
    redis:
      host: localhost
      port: 6379

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
      base-path: /actuator
  endpoint:
    health:
      show-details: always
  metrics:
    enable:
      all: true

flyway:
  enabled: true
  locations: classpath:db/migration
  baseline-on-migrate: false

app:
  cors:
    allowed-origins: "http://localhost:5173,http://localhost:3000,http://localhost:8000"
    allowed-methods: "GET,POST,PUT,DELETE"

jwt:
  cookie:
    name: COWRITE_SESSION_ID
  expiration: 3600000

rate:
  limit:
    requests: 30
    refill: 10
    duration:
      seconds: 30
